# Generated by Django 5.1.3 on 2024-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quiz",
            name="quiz_app_qu_start_t_ec56b5_idx",
        ),
        migrations.RemoveIndex(
            model_name="quizattempt",
            name="quiz_app_qu_quiz_id_d68651_idx",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
