# Generated by Django 5.1.3 on 2024-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
