# Generated by Django 5.1.3 on 2024-11-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_remove_choice_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
