version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quiz-application-postgres-1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    container_name: quiz-application-hasura-1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:mypassword@postgres:5432/mydb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_quiz_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
